
version: 2

models:
    - name: dim_country
      description: "country table"
      columns:
          - name: id
            description: "The primary key for this table"    
            tests:
                - unique
                - not_null
          - name: name
            description: ""
          - name: region
            description: ""
          - name: load_date
            description: ""
          - name: last_update_date
            description: ""
          - name: main_source
            description: ""

    - name: dim_customer
      description: "customer table"
      columns:
          - name: id
            description: "The primary key for this table"    
            tests:
                - unique
                - not_null
          - name: name
            description: ""
          - name: email
            description: ""
          - name : country_id
            description: ""
          - name: premium_customer
            description: ""
          - name: load_date
            description: ""
          - name: last_update_date
            description: ""
          - name: main_source
            description: ""

    - name: dim_product
      description: "product table"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: reference
            description: ""
          - name: name
            description: ""
          - name: category_id
            description: ""
          - name: category_name
            description: ""
          - name: price
            description: ""
          - name: load_date
            description: ""
          - name: last_update_date
            description: ""
          - name: main_source
            description: ""

    - name : dim_date
      descript: "dim_date"
      columns:
        - name: id_date
        - name: id_month
        - name: lb_month

    - name: fact_installation
      description: "installation table"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: name
            description: ""
          - name: description
            description: ""
          - name: product_id
            description: ""
          - name: customer_country_id
            description: ""
          - name: customer_id
            description: ""
          - name: installation_date
            description: ""
          - name: id_installation_date
          - name: price
            description: ""
          - name: load_date
            description: ""
          - name: last_update_date
            description: ""
          - name: main_source
            description: ""